defaults: &defaults
  invoices:
    class_name: "Invoice"
    index: "查看票据"
  tax_categories:
    class_name: "TaxCategory"
    index: "商品税收分类编码库"
  buyers:
    class_name: "Buyer"
    index: "客户信息库"
  admins:
    class_name: "all"
    email: "admin@qq.com"
  users:
    class_name: "User"
  roles:
    class_name: "Role" 
    super_admin: "超级管理员"
    buyer: "客户信息管理"
    tax_category: "商品税收分类编码库管理"
    invoice: "发票管理"
  permissions:
    super_admin: "管理系统所有资源"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
